#!/bin/bash
dir="$(dirname $0)/.."
find "$dir" \( -iname '*.c' -or -iname '*.cpp' -or -iname '*.cu' -or -iname '*.h' \) \
	\! -iname 'cmdline.h' \
	\! -ipath "$dir/lib/*" \
	\! -ipath "$dir/doc/*" \
	-exec clang-format -style=file -i {} +
